// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Item struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	Description     *string `json:"description,omitempty"`
	Category        *string `json:"category,omitempty"`
	Price           float64 `json:"price"`
	DepositRequired bool    `json:"depositRequired"`
	Availability    bool    `json:"availability"`
	Owner           *User   `json:"owner"`
}

type Mutation struct {
}

type Query struct {
}

type Rental struct {
	ID          string `json:"id"`
	Item        *Item  `json:"item"`
	Renter      *User  `json:"renter"`
	StartDate   string `json:"startDate"`
	EndDate     string `json:"endDate"`
	Status      string `json:"status"`
	DepositPaid bool   `json:"depositPaid"`
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Location string `json:"location"`
}
